import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://www.sojoee.com/wp-content/uploads/2023/09/FTW-1212-High-heel-womens-black-work-shoes-450x450.jpg",
    title: "Bull Pumps",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Gucci",
    color: "black",
    category: "heels",
  },
  {
    img: "https://images.yaoota.com/Eo4dDbISvqWpEZbBN6vXByJBNlk=/trim/yaootaweb-production-ng/media/crawledproductimages/3ce55c6a2a06257a6e04027e231110175e113c8b.jpg",
    title: "Tree Crystal",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Ego",
    color: "white",
    category: "heels",
  },

  {
    img: "https://ng.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/76/0543111/1.jpg?8537",
    title: "Simple Pointed",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Simmi",
    color: "black",
    category: "heels",
  },
  {
    img: "https://images.yaoota.com/zxavvaVMlEqwr28BOi2G4Q3LqV4=/trim/fit-in/500x500/filters:quality(80)/yaootaweb-production-ng/media/crawledproductimages/87b6bda26aa9e8794264b13db5a0e16d3ab19c68.jpg",
    title: "Yoota heels",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Ego",
    color: "red",
    category: "heels",
  },
  {
    img: "https://ng.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/37/970919/1.jpg?2372",
    title: "Flat Slip On Pumps",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Ego",
    color: "red",
    category: "flats",
  },
  {
    img: "https://www-konga-com-res.cloudinary.com/w_auto,f_auto,fl_lossy,dpr_auto,q_auto/media/catalog/product/W/Y/171090_1691455090.jpg",
    title: "Knit Flat",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Gucci",
    color: "blue",
    category: "flats",
  },

  {
    img: "https://images.yaoota.com/_UOHuWIHEZF-capT-fF0dhTXECs=/trim/yaootaweb-production-ng/media/crawledproductimages/27ae1a79d99dc9886ee9f3e4a12b407fb15c330c.jpg",
    title: "Basket Flats",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Zara",
    color: "white",
    category: "flats",
  },

  {
    img: "https://www.sojoee.com/wp-content/uploads/2022/04/FTW-1138b-Blue-Nubuck-egg-roll-ballerina-flat-office-womens-shoes-450x450.jpg",
    title: "Jooe flats",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Ego",
    color: "blue",
    category: "flats",
  },

  {
    img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
    title: "Nike Men's Sneaker",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Adidas",
    color: "blue",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "PUMA BLACK-OCE",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "green",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
    title: "Pacer Future Sneaker",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "red",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
    title: "Unisex-Adult Super",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "black",
    category: "sneakers",
  },
  {
    img: "https://img.kwcdn.com/product/Fancyalgo/VirtualModelMatting/634d26abc380deb7e63e4605d64b507d.jpg?imageView2/2/w/500/q/60/format/webp",
    title: "Roma feet",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Zara",
    color: "green",
    category: "heels",
  },
  {
    img: "https://img.kwcdn.com/product/Fancyalgo/VirtualModelMatting/f4dd78ba0134caf9878493280a5f8d12.jpg?imageView2/2/w/500/q/60/format/webp",
    title: "Pacer Future",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Gucci",
    color: "blue",
    category: "heels",
  },

  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnaiWkJKGlWe0iUsLNJhTcoacsa2rX303YbwgAhgd5A7ncsDeFJu6V_wcUA_hhW62JerY&usqp=CAU",
    title: "Fusion Evo ",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Simmi",
    color: "white",
    category: "heels",
  },
  {
    img: "https://www.lestyleparfait.co.ke/cdn/shop/files/ladies-luxury-high-heels-wedding-shoes-lestyleparfait-kenya-1.jpg?v=1691098848",
    title: "Rainbow Chex",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Gucci",
    color: "blue",
    category: "heels",
  },
  {
    img: "https://img.kwcdn.com/product/Fancyalgo/VirtualModelMatting/23217a2a9aeeb71b8677416174cde75b.jpg?imageView2/2/w/500/q/60/format/webp",
    title: "Low-Top flat",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Ego",
    color: "green",
    category: "flats",
  },
  {
    img: "https://www-konga-com-res.cloudinary.com/w_auto,f_auto,fl_lossy,dpr_auto,q_auto/media/catalog/product/D/R/140823_1612646504.jpg",
    title: "Ego feet",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Ego",
    color: "black",
    category: "sandals",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNfgRfcnqPI9aGFnllJ8-QqEW9v8cPUtbtXw&usqp=CAU",
    title: "Classic flats",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Simmi",
    color: "white",
    category: "flats",
  },
  {
    img: "https://ng.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/65/7983032/2.jpg?7583",
    title: "Chunky flat",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Zara",
    color: "blue",
    category: "flats",
  },
  {
    img: "https://cartnear.s3.us-east-2.amazonaws.com/ng/ffaadcc8da6fd0a6f0edffacd50964da.jpg",
    title: "bf shoe",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Gucci",
    color: "black",
    category: "flats",
  },
  {
    img: "https://images.yaoota.com/LyChc5ICoR149D-R8JXtJswzSRE=/trim/yaootaweb-production-ng/media/crawledproductimages/7737d9a446bdc761eacbed68828a0f15dd40c1c1.jpg",
    title: "Pk cart",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Simmi",
    color: "red",
    category: "flatss",
  },
  {
    img: "https://www-konga-com-res.cloudinary.com/w_400,f_auto,fl_lossy,dpr_3.0,q_auto/media/catalog/product/Q/F/156178_1648984002.jpg",
    title: "Block heel",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Simmi",
    color: "green",
    category: "heels",
  },

  {
    img: "https://m.media-amazon.com/images/I/71+W3M9rdMS._AC_UF894,1000_QL80_.jpg",
    title: "Reina sandals",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Zara",
    color: "white",
    category: "sandals",
  },
  {
    img: "https://image.doba.com/dg9-nFqZTusoKPVc/2022-brand-new-female-sandals-mixed-color-hook-loop-platform-cool-sandals-women-rome-retro-casual-leisure-women-shoes.webp",
    title: "Rainbow trekkers",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Gucci",
    color: "all",
    category: "sandals",
  },
  {
    img: "https://www.sojoee.com/wp-content/uploads/2023/02/FTW-1198-Black-party-womens-high-heel-sandals-450x450.jpg",
    title: "Amore Stilettos",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Simmi",
    color: "black",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/610KQDaTgeL._AC_UY1000_.jpg",
    title: "Bridal Sandals Glitter",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "80",
    company: "Simmi",
    color: "white",
    category: "heels",
  },
  {
    img: "https://www-konga-com-res.cloudinary.com/w_auto,f_auto,fl_lossy,dpr_auto,q_auto/media/catalog/product/S/B/154566_1595897409.jpg",
    title: "Classy female",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "80",
    company: "Zara",
    color: "black",
    category: "sandals",
  },
];

export default data;